### ISSUE TITLE
Github Desktop 样式

### ISSUE THREAD

**Issue by leslieeilsel** [legend80s/commit-msg-linter#12]
使用 Github Desktop 提交时，样式显示有点问题。
![image](https://user-images.githubusercontent.com/25165449/129296007-49fce6c9-f0ba-444b-bb51-27fcaca388b1.png)

**Comment by legend80s** [comment]
好的 我们修复下

**Comment by legend80s** [comment]
试试 git-commit-msg-linter@3.2.7 
@leslieeilsel

**Comment by leslieeilsel** [comment]
已修复，多谢！
![微信截图_20210817102236](https://user-images.githubusercontent.com/25165449/129653833-4e81bbef-bd41-4390-8a76-a1ae2384de97.png)

**Comment by leslieeilsel** [comment]
> 试试 git-commit-msg-linter@3.2.7
> @leslieeilsel
