### ISSUE TITLE
It shouldn't be installed globally?

### ISSUE THREAD

**Issue by clluiz** [legend80s/commit-msg-linter#17]
In the docs you say to install using the command:

`npm install git-commit-msg-linter --save-dev`

But in the docs the command used is gcam "message".

For this command work we shouldn't install it globally?

**Comment by legend80s** [comment]
It shouldn't be installed globally because `gcam` is  alias for `git commit -am` 😄. Sorry for the docs, I will change it to `git commit -am`.
