### ISSUE TITLE
How to limit the language used by the commit message

### ISSUE THREAD

**Issue by alleluya-young** [legend80s/commit-msg-linter#22]
is there any way to set commit message only be in English?

**Comment by legend80s** [comment]
is this what you expected?
```
Pass: "docs: hello word"
Not Pass: "docs: 你好世界"
```

**Comment by alleluya-young** [comment]
> is this what you expected?
> 
> ```
> Pass: "docs: hello word"
> Not Pass: "docs: 你好世界"
> ```

yes, I want only en commit message can pass

**Comment by legend80s** [comment]
Supported in v4.2.1

### Usage

commitlinterrc.json
```json
{
  "englishOnly": true
}

```

**Comment by alleluya-young** [comment]
> Supported in v4.2.1
> 
> ### Usage
> commitlinterrc.json
> 
> ```json
> {
>   "englishOnly": true
> }
> ```

thanks a lot, it works!
