### ISSUE TITLE
feat: `install.js` support `--silent` option

### ISSUE THREAD

**Issue by zanminkian** [legend80s/commit-msg-linter#25]
Run `node node_modules/git-commit-msg-linter/install.js` will print some logs what I don't need. Support `node node_modules/git-commit-msg-linter/install.js --silent` to keep quiet.

**Comment by zanminkian** [comment]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/35495628/218097209-d644bff7-71f9-4308-a459-52c545ce13e8.png">

I have a private tool will run `node node_modules/git-commit-msg-linter/install.js` manually at the postinstall stage. I don't want to see the logs of `[git-commit-msg-linter]`.

It will be useful for the tools which want to integrate with `commit-msg-linter`.

**Comment by legend80s** [comment]
`silent` flag added in `git-commit-msg-linter@4.6.0`.

**Comment by legend80s** [comment]
If it works please let me know 😄.

**Comment by zanminkian** [comment]
Thank you @legend80s . I made a PR to support this feature better. Please consider #28.
