### ISSUE TITLE
global install

### ISSUE THREAD

**Issue by Linyutau** [legend80s/commit-msg-linter#5]
你好，请问这支持全局安装吗

**Comment by legend80s** [comment]
不支持，因为是修改的项目目录下的 ./.git/hooks/commit-msg 钩子，我们也推荐按照项目维度安装。

你的真实诉求是？

**Comment by Linyutau** [comment]
> 不支持，因为是修改的项目目录下的 ./.git/hooks/commit-msg 钩子，我们也推荐按照项目维度安装。
> 
> 你的真实诉求是？

谢谢你的回复，我们团队涉及的项目可能比较多，我希望的是他们在安装这个钩子时是尽量无感知的，能够让我的小伙伴在进行git init的时候将钩子copy到对应的hooks目录下。
目前我在试着单独写个commit-message的钩子来校验。

**Comment by legend80s** [comment]
> > 不支持，因为是修改的项目目录下的 ./.git/hooks/commit-msg 钩子，我们也推荐按照项目维度安装。
> > 你的真实诉求是？
> 
> 谢谢你的回复，我们团队涉及的项目可能比较多，我希望的是他们在安装这个钩子时是尽量无感知的，能够让我的小伙伴在进行git init的时候将钩子copy到对应的hooks目录下。
> 目前我在试着单独写个commit-message的钩子来校验。

好的，如果有任何问题可随时交流
