### ISSUE TITLE
field additional information 

### ISSUE THREAD

**Issue by renatoassis01** [legend80s/commit-msg-linter#6]
Hello good job! Thank you for creating this wonderful lint.

You have the possibility to include a field of
additional information in `commitlinterrc.json` and display along with other information?

**Comment by legend80s** [comment]
Can you make a PR? or Show a demo of what usually is the content of additional information and where it should be placed.

**Comment by legend80s** [comment]
A header or a footer or both?

**Comment by renatoassis01** [comment]
Hi,

just below the subject.

It would be to show a help text with a link to documentation.

I'm using the subject field for this

**Comment by legend80s** [comment]
OK let me do it 😄

**Comment by legend80s** [comment]
Does this meet your requirement?

![image](https://user-images.githubusercontent.com/8603442/112172864-0713f780-8c30-11eb-8439-a38a8f55bb57.png)

commitlinterrc.json

```json
{
  "postSubjectDescriptions": [
    "You have the possibility to include a field of additional information in commitlinterrc.json by using `postSubjectDescriptions` and display along with other information",
    "see more configuration details at https://github.com/legend80s/commit-msg-linter#commitlinterrcjson"
  ]
}
```

**Comment by renatoassis01** [comment]
Hello @legend80s, 

that's exactly it. Thank you very much for making this feature available. It will be very useful.

Thank you very much!

**Comment by legend80s** [comment]
+ git-commit-msg-linter@3.1.0
