### ISSUE TITLE
The package is not working with husky v5

### ISSUE THREAD

**Issue by vinicius91carvalho** [legend80s/commit-msg-linter#8]
The issue #7 was not resolved. I'm trying to use your last solution @legend80s, but I'm receiving the error below:

ℹ No staged files match any configured task.
(node:98010) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
at readFile (fs.js:326:10)
at internal/util.js:297:30
at new Promise ()
at readFile (internal/util.js:296:12)
at main (/Users/viniciuscarvalho/Projects/hub-api/.git/hooks/commit-msg:47:5)
at Object. (/Users/viniciuscarvalho/Projects/hub-api/.git/hooks/commit-msg:56:1)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
at Module.load (internal/modules/cjs/loader.js:928:32)
at Function.Module._load (internal/modules/cjs/loader.js:769:14)
(Use node --trace-warnings ... to show where the warning was created)
(node:98010) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:98010) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[feat/signup 656afe6] asdfsdaf
1 file changed, 6 insertions(+), 6 deletions(-)

**Comment by legend80s** [comment]
1 Can you show the file content of `.husky/commit-msg`?
2 In the `./.git/hooks/commit-msg` add the console log to find out what's in the argv

<p align="center"><img src="https://user-images.githubusercontent.com/8603442/111329396-10d6b180-86aa-11eb-90fd-87a53457ec1d.png" width="55%" />

---

In my project

1. `cat .husky/commit-msg`

```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

.git/hooks/commit-msg $1
```

husky will pass the file path of your commit msg as `$1`.

2 `gcam "test"`

```
> husky-5-not-work-with-gcmsglinter@1.0.0 test /Users/liuchuanzong/workspace/playground/husky-5-not-work-with-gcmsglinter
> echo "Error: no test specified" && exit 0

Error: no test specified
process.argv: [
  '/Users/***/.nvm/versions/node/v12.8.1/bin/node',
  '/Users/***/workspace/playground/husky-5-not-work-with-gcmsglinter/.git/hooks/commit-msg',
  '.git/COMMIT_EDITMSG'
]
```

The key point here is `'.git/COMMIT_EDITMSG'` as git store it's commit msg content in this temp file and it is passed as `$1` by husky V5.

**Comment by vinicius91carvalho** [comment]
1) The file content of `.husky/commit-msg`:

![Screen Shot 2021-03-16 at 12 08 28](https://user-images.githubusercontent.com/12401263/111332177-52d30980-8650-11eb-83ca-363cd30b4264.png)

2) The value of `process.argv` as you ask me:

```bash
viniciuscarvalho in hub-api on  feat/signup [+] 
❯ git commit -m "testasasa"
ℹ No staged files match any configured task.
[
  '/Users/viniciuscarvalho/.asdf/installs/nodejs/14.15.1/bin/node',
  '/Users/viniciuscarvalho/Projects/hub-api/.git/hooks/commit-msg'
]
(node:46268) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at readFile (fs.js:326:10)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
```

**Comment by vinicius91carvalho** [comment]
I found the error.  When I run the command: 

`npx husky add .husky/commit-msg ".git/hooks/commit-msg \$1"`

The file was generated with the content below:

![Screen Shot 2021-03-16 at 12 14 45](https://user-images.githubusercontent.com/12401263/111333182-34214280-8651-11eb-924b-0cfe8521caaa.png)

It was created without the parameter `$1`. Add this, it solves the problem.

Thanks @legend80s for your help.

**Comment by 4lessandrodev** [comment]
`npx husky add .husky/commit-msg ".git/hooks/commit-msg \$1"` the command create file without `$1`

```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

.git/hooks/commit-msg $1
```

**Comment by LuigiMaestrelli** [comment]
I just remove husky and commit-msg-linter and added everything again.
It seams to be working now.

**Comment by jeanvcastro** [comment]
On the current date if you add the git-commit-msg-linter before the husky will stop working. To fix it, just add it back to your dependencies and it will work fine.

Also, the command described earlier must be run.

> ```shell
> npx husky add .husky/commit-msg ".git/hooks/commit-msg \$1"
> ```
