### ISSUE TITLE
Husky 6 configuration

### ISSUE THREAD

**Issue by LuigiMaestrelli** [legend80s/commit-msg-linter#9]
Does it take some additional configuration to work with Husky 6?
Husky is up and running and the commit-msg-linter is installed but it does not run any validations.

My envirioment:
node 15.14.0
git-commit-msg-linter 3.1.0
husky 6.0.0
git version 2.30.2.windows.1

Tks

**Comment by legend80s** [comment]
https://github.com/legend80s/commit-msg-linter/issues/8#issuecomment-800353759

**Comment by LuigiMaestrelli** [comment]
I tried that.
it gives me an error on commit "Error: ENOENT: no such file or directory, open 'C:\.git\COMMIT_EDITMSG'"
Obviously that directory is not valid

**Comment by LuigiMaestrelli** [comment]
I just remove husky and commit-msg-linter and added again.
It seems to be working now.
